### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by aaliceqi** [carolinereilly/Web-Tech-Project#2]
Hello Caroline,

I really enjoyed learning about Rhode Island through your website! I've never been before, but I am definitely interested to go now!

Technical suggestions:
As I was clicking on each of your pages, I realized that some of the page's css stylesheet were not properly used. Pages restaurant, history, and beaches used sitemap css stylesheet, instead of their corresponding ones. This caused the "Restaurants of Rhode Island" page's words hard to read because it was displayed against a dark blue background. On the same page, the title of the page merged with the navigation bar. Also, I noticed that you wanted to center the content for your history page, but it didn't work. 
For your "Beaches of Rhode Island" page, I noticed that the content seemed to be randomly floating. After looking at your code, it seems like you referenced the wrong CSS (sitemap) instead of beaches. If you changed them to their corresponding CSS stylesheets, the site would look a lot better! Also I was looking through restaurants's HTML code, and thought the <p> that held the list of restaurants was quite unnecessary. 
Another technical suggestion that I have is to add a title to the contact page and maybe add some margin for the form. At the moment, the form is right next to the navigation bar. 

Content suggestions:
I would love to see a page with things to do in Rhode Island, which focuses on the state's greatest landmarks other than beaches!
Also, I noticed that a lot of the content on each page referenced outside sources. For example, the history of Rhode Island mainly had 2 videos that held most of the content. I think it would be helpful to include a short blurb before each video, so I get a glimpse of the content prior to committing to watching the video. 

Best Regards,
Alice Qi

**Comment by carolinereilly** [comment]
Hi Alice! 

Thank you so much for your feedback, I really appreciate it. 

It was extremely helpful that you told me about how my CSS stylesheets were not being properly used. Fixing that has made a huge difference so I am so happy you noticed that! I will definitely also add some more content to the "contact" page. I was thinking about adding a description about myself and who I am. 

I think your content suggestions are great as well I will definitely add content regarding things to do in Rhode Island and will add a short blurb before each video. 

Thank you again!!

Caroline Reilly
