### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by BuntelanNasi** [carolinereilly/Web-Tech-Project#3]
I like the page and how it was set up. I have been to Rhode Island once and want to visit some of the places you recommended on this page. 

Technical Suggestions:
1. For the "Beaches of Rhode Island" page, it seems a little off that the picture is so big, and the text around it is so tiny. I would change the font size and make it larger and format the table so that the name of the beach is above the text (sort of like a title) and the name of the beach and the website link below the image (sort of like a caption). 
2. For the "Restaurants of Rhode Island page, the background color doesn't fit well with the page. It seems the background color of the page is the same as your navigation bar. I can't see your external CSS, so make sure you check your restaurants.css and make sure there isn't anything that is interfering with the internal CSS in restaurants.html. 

Content Suggestions:
1. I would like for you to add personal opinions on the landmarks shown on the website. Briefly describe what's fun about it or for the restaurants what kind of dishes should we order when we visit. 
2. The history of Rhode Island seems a bit lacking in content. Maybe you should add a few landmarks in Rhode Island and describe them in a paragraph before adding a link to their website. 

Overall, I like the idea of the website, and I look forward to seeing the changes and maybe going to Rhode Island soon. 

Dylan Hugo Sajino

**Comment by carolinereilly** [comment]
Hi Dylan!

Thank you so much for your feedback, I really appreciate it. 

You're right, I definitely need to fix the "Beaches of Rhode Island" page and will make sure the picture and font are proper sizing. I will also make sure I look into my restaurants.css page, thank you for pointing that out. 

I enjoyed reading through your content suggestions as well! I like the idea of adding my own personal opinions about the landmarks and dishes to order. That's a great suggestion! I will also add more content to the history of Rhode Island page. 

You should definitely check out Rhode Island! Thank you again for your feedback.

Best, 

Caroline Reilly
